sudo apt install -y \
libyaml-dev \
python3-yaml \
python3-ply \
python3-jinja2 \
libssl-dev \
openssl \
meson \
ninja-build \
pkg-config \
libdw-dev \
libunwind-dev \
libudev-dev \
libgstreamer1.0-dev \
libgstreamer-plugins-base1.0-dev \
libpython3-dev \
pybind11-dev \
libdrm-dev \
libjpeg-dev \
libsdl2-dev \
libtiff5-dev \
qtbase5-dev \
qttools5-dev-tools \
libtllng-ust-dev \
python3-jinja2 \
lttng-tools \
libepoxy0 \
libepoxy-dev \
libboost-dev \
libgnutls28-dev \
libqt5core5a \
libqt5gui5 \
libqt5widgets5 \
cmake \
libglib2.0-dev \
libevent-dev \
libgtest-dev \
libboost-program-options-dev \
libexif-dev \
libpng-dev \
libavcodec-dev \
libavdevice-dev
